! Website: https://projecteuler.net/archives
! Project Euler 
! Problem - 2

! --------------------------------------------------------------------------------------------
! Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
! By starting with 1 and 2, the first 10 terms will be:
! 1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
! By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
! find the sum of the even-valued terms.
! --------------------------------------------------------------------------------------------

program proj_euler_p2
    implicit none
    
    integer :: num_1, num_2, num_3, sum

    num_1 = 1
    num_2 = 2
    num_3 = 0
    sum = 2
    do 
        num_3 = num_1 + num_2
        if (num_3 > 4e6) then         
            exit                     
        end if
        
        num_1 = num_2
        num_2 = num_3
        
        if (mod(num_3,2)==0) then
            sum = sum + num_3
        
        end if
    end do
    print*, 'Sum is =', sum
end program proj_euler_p2












